config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  authenticate :user, lambda { |user| user.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "users/registrations", confirmations: "users/confirmations" }

  root to: "home#index"

  resources :events, only: [:index] do
    collection do
      get 'update_user'
    end
  end
  resources :meals, only: [:index, :show]
  resources :comments, only: [:create]
  resources :pepeato, only: [:index]

  resource :profile, only: [:show, :edit, :update] do
    collection do
      get 'rating'
    end
    collection do
        get 'croping'
        get 'webhook'
        get 'bank_account'
        patch 'update_picture'
        patch 'update_bank_account'
    end
  end
  resources :publics, only: [:index, :show] do
    collection do
      get 'faq'
      get 'photo'
    end
  end

  namespace :profile do
    resources :chief_pictures, only: [:destroy, :new, :create, :update]
    resources :meal_pictures, only: [:destroy, :new, :create, :update]
    resources :meals do
      collection do
        get 'mealpic'
        get 'mealcrop'
        get 'history'
        get 'validation'
        patch 'update_portion'
      end
    end
    resources :orders do
      resources :payments, only: [:new, :create]
      collection do
        get 'history'
        get 'rating'
        get 'validation'
      end
    end
  end
end

app/controllers/profile/chief_pictures_controller.rb
module Profile
  class ChiefPicturesController < ApplicationController

    before_action :authenticate_user!

    def create
      @user = current_user
      @chief_picture = @user.chief_pictures.build(chief_picture_params)
      if @chief_picture.save
        redirect_to croping_profile_path(@chief_picture)
      else
        render :new
      end
    end

    def new
      @user = current_user
      @chief_picture = ChiefPicture.new
    end

    def update
      @user = current_user
      @chief_picture = current_user.chief_pictures.find(params[:id])
      @chief_picture.update(chief_picture_params)

      if @chief_picture.update(chief_picture_params)
        redirect_to profile_path
      else
        render :new
      end
    end

    def destroy
      @chief_picture = current_user.chief_pictures.find(params[:id])
      @chief_picture.destroy
      redirect_to profile_path
    end

    private

    def chief_picture_params
      params.require(:chief_picture).permit(:chiefpicture, :chiefpicture_original_w, :chiefpicture_original_h, :chiefpicture_box_w, :chiefpicture_aspect, :chiefpicture_crop_x, :chiefpicture_crop_y, :chiefpicture_crop_w, :chiefpicture_crop_h)
    end
  end
end

app/controllers/profile/meal_pictures_controller.rb
module Profile
  class MealPicturesController < ApplicationController

    before_action :authenticate_user!

    def create
      @meal = Meal.find(params[:meal_id])
      @user = current_user
      @meal_picture = @meal.meal_pictures.build(meal_picture_params)
      if @meal_picture.save
        redirect_to mealcrop_profile_meals_path(@meal_picture, meal_id: params[:meal_id])
      else
        render :new
      end
    end

    def new
      @user = current_user
      @meal_picture = MealPicture.new
    end

    def destroy
      @meal = Meal.find(params[:meal_id])
      @meal_picture = @meal.meal_pictures.find(params[:id])
      @meal_picture.destroy
      redirect_to mealpic_profile_meals_path(meal_id: @meal.id)
    end

    def update
      @meal = Meal.find(params[:meal_id])
      @meal_picture = @meal.meal_pictures.find(params[:id])
      @meal_picture.update(meal_picture_params)

      if @meal_picture.update(meal_picture_params)
        redirect_to mealpic_profile_meals_path(meal_id: @meal.id)
      else
        render :new
      end
    end

    private

    def meal_picture_params
      params.require(:meal_picture).permit(:picture, :picture_original_w, :picture_original_h, :picture_box_w, :picture_aspect, :picture_crop_x, :picture_crop_y, :picture_crop_w, :picture_crop_h)
    end
  end
end

app/controllers/profile/meals_controller.rb
module Profile
  class MealsController < ApplicationController

    before_action :authenticate_user!
    before_action :is_chief?
    before_action :set_meal, only: [:is_ordered, :show, :edit, :update, :destroy]
    before_action :has_stripe?, only: [:new]
    before_action :is_ordered?, only: [:edit, :update]

    def validation
      @order = Order.find(params[:format])
      ch = Stripe::Charge.retrieve(@order.charge)
      if !ch.captured
        ch.capture
        @order.update(payment_validation: 'true')
        redirect_to profile_meals_path
      else
        redirect_to profile_meals_path
      end
    end

    def index
      @user = current_user
      @meals = policy_scope(Meal)
      @meals = current_user.meals
    end

    def show
    end

    def new
      @user = current_user
      @meal = Meal.new
      authorize @meal
    end

    def create
      @meal = current_user.meals.new(meal_params)
      authorize @meal
      if @meal.save
        MealMailer.creation(@meal.id).deliver_now
        MealMailer.delay_for(5.minutes).validation(@meal.id)

        if !@meal.user.bank_account_id
          MealMailer.delay_for(10.minutes).remember_rib(@meal.id)
        end

        current_user.update(last_meal: DateTime.now)

        if params[:pictures]
          params[:pictures].each { |picture|
            @meal.meal_pictures.create(picture: picture)
          }
        end
         redirect_to mealpic_profile_meals_path(meal_id: @meal.id)
      else
        render :new
      end
    end

    def edit
      @user = current_user
      authorize @meal
    end

    def update
      authorize @meal
      @meal.update(meal_params)
      if @meal.save
        if params[:pictures]
          params[:pictures].each {|picture|
          @meal.meal_pictures.create(picture: picture )
          }
        end
        redirect_to profile_meals_path
      else
        render :edit
      end
    end

    def update_portion
      @meal = Meal.find(params[:format])
      @meal.update(portion_params)
      if @meal.save
        flash[:notice] = 'Le nombre de menus a été modifié'
        redirect_to profile_meals_path
      else
        flash[:notice] = "Nous n'avons pas pu modifier le nombre de menus"
        redirect_to profile_meals_path
      end
    end

    def mealpic
      @meal_picture = MealPicture.new
      @meal = current_user.meals.find(params[:meal_id])
    end

    def mealcrop
      @meal = current_user.meals.find(params[:meal_id])
      @picture = @meal.meal_pictures.find(params[:format])
    end

    def set_meal
      @meal = current_user.meals.find(params[:id])
    end

    def destroy
      authorize @meal
      MealMailer.cancel(@meal.id).deliver_now
      @meal.destroy
      redirect_to profile_meals_path
    end

    def history
      @meals = policy_scope(Meal)
      @meals = current_user.meals
    end

    private

    def is_chief?
      if current_user.chief?
        true
      else
        render :text =>" Ce n'est pas bien de taper des URL au pif. Si vous voulez cuisiner postulez en tant que chef Pepeat"
      end
    end


    def is_ordered?
      if @meal.orders.where(state: "paid").sum(:portion)
        true
      else
        render :text =>" Ce n'est pas bien de taper des URL au pif.Vous ne pouvez supprimer un plat avec des commandes"
      end
    end

    def has_stripe?
      if current_user.stripe_id
        true
      else
        redirect_to profile_path, notice: "Vous devez entrer vos données bancaire avant de créer un menu."
      end
    end

    def portion_params
      params.require(:meal).permit(:portion)
    end

    def meal_params
      params.require(:meal).permit(:cgu, :ingredients, :validation, :home_hour, :home, :starter, :main, :dessert, :price, :title, :portion, :description, :start_hour, :end_hour, :day, :picture, :takeaway)
    end

  end
end

app/controllers/profile/orders_controller.rb
module Profile
  class OrdersController < ApplicationController

    before_action :authenticate_user!
    before_action :set_order, only: [:show, :update, :destroy, :charged]

    def index
      @orders = policy_scope(Order)
      @orders = current_user.orders.all
    end

    def new
      @meal = Meal.find(params[:order][:meal_id])
      @order = Order.new
      authorize @order
    end

    def create
      @meal = Meal.find(params[:order][:meal_id])
      @order = @meal.orders.build(order_params)
      authorize @order
      @order.user = current_user
      if @order.save
        redirect_to new_profile_order_payment_path(@order)
      else
        render :new
      end
    end

    def show
      @markers = Gmaps4rails.build_markers(@order) do |order, marker|
        marker.lat order.meal.user.latitude
        marker.lng order.meal.user.longitude
      end
    end

    def validation
      @order = Order.find(params[:format])
      ch = Stripe::Charge.retrieve(@order.charge)
      if !ch.captured
        ch.capture
        @order.update(payment_validation: 'true')
        redirect_to profile_orders_path
        flash[:notice] = 'La réception a été validé'
      else
        redirect_to profile_orders_path
        flash[:notice] = 'Vous avez déja validé la réception'
      end
    end

    def edit
      authorize @order
    end

    def destroy
      if @order.meal.day > DateTime.now.to_date
        PaymentMailer.cancel_before(@order.id).deliver_now
        PaymentMailer.cancel_before_user(@order.id).deliver_now
        @order.destroy
        redirect_to profile_orders_path
      else
        ch = Stripe::Charge.retrieve(@order.charge)
        if !ch.captured
          ch.capture
          @order.update(payment_validation: 'true')
        end
        PaymentMailer.cancel_after(@order.id).deliver_now
        PaymentMailer.cancel_after_user(@order.id).deliver_now
        @order.destroy
        redirect_to profile_orders_path
      end
    end

    def history
      @orders = policy_scope(Order)
      @orders = current_user.orders.all
      @markers = Gmaps4rails.build_markers(@orders) do |order, marker|
        marker.lat order.meal.user.latitude
        marker.lng order.meal.user.longitude
      end
    end

    def rating
      @order = Order.find(params[:id])
    end

    def update
      if params[:order][:review] != nil
        @order = Order.find(params[:id])
        authorize @order
        @order.update(review_params)
        redirect_to history_profile_orders_path
      end
    end

    private

    def set_order
      @order = current_user.orders.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:portion, :meal_id, :amount, :state )
    end

    def review_params
      params.require(:order).permit(:review)
    end

  end
end

app/controllers/profile/payments_controller.rb
module Profile
  class PaymentsController < ApplicationController

    before_action :set_order
    before_action :filled_profile?

    def filled_profile?
      if current_user.picture && current_user.firstname && current_user.lastname && current_user.phone_number
        true
      else
        flash[:notice] = 'Vous devez remplir votre profil pour commander un plat'
        redirect_to edit_profile_path
      end
    end

    def new
      @client = 0.15
      @chief = 0.04
    end

    def create
      @client_amount = 1.15
      @client = 0.15
      @chief = 0.04

      @amount = @order.amount_cents * @order.portion.to_i * @client_amount

      if current_user.customer_id
        customer = Stripe::Customer.retrieve(current_user.customer_id)
      else
        customer = Stripe::Customer.create(
          email: params[:stripeEmail],
          card:  params[:stripeToken]
        )
        current_user.update(customer_id: customer.id)
      end

      # store this customer id and re-use it.
      @commission = @order.amount_cents * @order.portion.to_i * @client + @order.amount_cents * @order.portion.to_i * @chief
      charge = Stripe::Charge.create({
        customer: customer.id,
        amount:       @amount.to_i,  # in cents
        description:  "#{@order.user.firstname} a commandé #{@order.portion} menus #{@order.meal.title} au cuisniner #{@order.meal.user.surname}",
        currency:     'eur',
        destination: @order.meal.user.stripe_id,
        capture: 'false',
        application_fee: @commission.to_i
      })
      @order.update(payment: charge.to_json, state: 'paid', charge: charge.id)
      current_user.update(number_orders: current_user.number_orders.to_i + 1, last_order: DateTime.now)
      @order.meal.user.update(number_meals_sold: @order.meal.user.number_meals_sold.to_i + @order.portion.to_i, ca: @order.meal.user.ca.to_i + @order.portion.to_i * (@order.amount_cents.to_i / 100 ))

      StripeJob.delay_until(@order.meal.day + 23.hour).perform_later(@order.id)
      PaymentMailer.delay_until(@order.meal.day + 41.hour).review(@order.id)
      PaymentMailer.confirmation(@order.id).deliver_later
      PaymentMailer.new_order(@order.id).deliver_later
      PaymentMailer.delay_until(@order.meal.day).remember(@order.id)

      redirect_to profile_orders_path

      rescue Stripe::CardError => e
      flash[:error] = e.message
      flash[:notice] = "Votre carte n'a pas été acceptée. Rapprochez vous de votre banque pour connaître la raison."
      redirect_to new_profile_order_payment_path(@order)
    end

  private

    def set_order
      @order = Order.where(state: 'pending').find(params[:order_id])
    end
  end
end

app/views/profiles/bank_account.html.erb
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">
Stripe.setPublishableKey('pk_live_sWVpuv2ZeZ89PDsjU7Lx678w')
</script>

<div class="background-bank window-height">
  <div class="overlay">
    <div class="background-bank-title text-center">
      <h3>Votre compte bancaire</h3>
      <% if current_user.bank_account_id %>
        <% account = Stripe::Account.retrieve(current_user.stripe_id) %>
        <% bank_account = account.external_accounts.retrieve(current_user.bank_account_id) %>
        <h4>Actuel : ********<%= bank_account.last4 %></h4>
        <p>Changer de compte bancaire</p>
        <div class="background-bank-form">
        <%= form_for(current_user, url: update_bank_account_profile_path, html: { id: "bank_account_form"} ) do |f| %>
            <div class= "bank-input">
              <input type="text" class= "account-number form-control" />
            </div>
            <div id="notice"></div>
            <%= f.submit "Enregistrement du nouveau compte",  class: "btn btn-pepeat " %>
            <p>En enregistrant votre compte bancaire vous agréez à nos <%= link_to 'CGU', '#' %> et à <%= link_to "l'agrément des des comptes connectés Stripe", 'https://stripe.com/connect/account-terms', target: 'blank' %></p>
          <% end %>
        </div>
      <% else %>
        <p>Ajouter un compte bancaire</p>
        <div class="background-bank-form">
          <%= form_for(current_user, url: update_bank_account_profile_path, html: { id: "bank_account_form"} ) do |f| %>
              <div class= "bank-input">
                <input type="text" class= "account-number" />
              </div>
              <div id="notice"></div>
              <%= f.submit "Enregistrement du compte",  class: "btn btn-pepeat " %>
              <p>En enregistrant votre compte bancaire vous agréez à nos <%= link_to 'CGU', '#' %> et à <%= link_to "l'agrément des des comptes connectés Stripe", 'https://stripe.com/connect/account-terms' %></p>
          <% end %>
        </div>
      <% end %>
      </div>
    </div>
  </div>

app/views/profiles/croping.html.erb
<div class="background-profile-show background-banner">
  <div class="overlay">
    <div class="background-profile-show-title text-center">
      <h3>Les photos de votre cuisine</h3>
      </div>
    </div>
  </div>
</div>

<%= simple_form_for @picture, url: profile_chief_picture_path(@picture) do |f| %>
  <div class="container">
    <div class="crop-tool">
      <h1 class= "text-center profile-header">Outil sublimation de photo</h1>
      <div class="row">
        <div class="col-xs-8">
          <div class= "crop-tool-picture">
            <%= f.cropbox :chiefpicture, :width => 680 %>
          </div>
        </div>
        <div class="col-xs-4">
          <div class= "crop-tool-preview text-center">
            <h3 class= "text-center">Photo telle qu'elle apparaitra sur Pepeat</h3>
            <%= f.crop_preview :chiefpicture, :width => 300 %>
            <div class= "text-center crop-tool-button">
              <%= f.button :submit, "Ma photo est belle", class: "btn-lg btn-pepeat" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/profiles/rating.html.erb
<% if review(@user) == 0 %>
  <div class="background-default window-height">
    <div class= "background-default-blur">
      <div class="background-default-blur-text">
        <h3 class= "text-center">Vous n'avez aucun avis</h3>
      </div>
      <div class="background-default-blur-edit">
        <%= link_to 'Créer un menu', new_profile_meal_path, class: "btn btn-pepeat btn-large" %>
      </div>
    </div>
  </div>
<% else %>
  <div class="background-meals-show background-banner">
    <div class="overlay">
      <div class="background-meals-show-title text-center">
        <h3>Tous mes avis</h3>
        <%= image_tag @user.picture.url(:medium), class: "img-circle banner-review-pic" %>
      </div>
    </div>
  </div>
  <% @user.meals.each do |meal| %>
    <%= render '/shared/review', meal: meal %>
  <% end %>
<% end %>

app/views/profiles/show.html.erb
<% if @user.picture.nil? || @user.firstname.nil? || @user.lastname.nil? %>
  <div class="background-default window-height">
    <div class= "background-default-blur">
      <div class="background-default-blur-text">
        <h3 class= "text-center">Vous n'avez pas rempli votre profil</h3>
      </div>
      <div class="background-default-blur-edit">
        <%= link_to 'Je remplis mon profil', edit_profile_path, class: "btn btn-pepeat btn-lg" %>
      </div>
    </div>
  </div>
<% else %>

<div class="background-profile-show background-banner">
  <div class="overlay">
    <div class="background-profile-show-title text-center">
      <h3>Votre profil</h3>
      </div>
    </div>
  </div>
</div>

<% if current_user.chief? %>
<ul class="nav nav-pills nav-justified">
  <li role="presentation"><a href=".1">Mes informations</a></li>
  <li role="presentation"><a href=".3">Mes informations bancaires</a></li>
  <li role="presentation"><a href=".4">Ma galerie photo</a></li>
  <li role="presentation"><a href=".5">Mes avis</a></li>
</ul>

  <div class="container">
    <div class="chief-profile 1">
      <h1 class= "text-center profile-header">Mes informations</h1>
      <div class="row">
        <div class="col-xs-12 col-sm-6">
          <div class="chief-profile-left text-center">
            <div class= "classic-pic">
              <%= image_tag @user.picture.url(:large), class: "user-img img-circle" %>
              </br>
              <div class= "btn btn-success2 crop">
                Redimensionner
              </div>
            </div>
            <div class= "hidden-form cropable">
              <%= form_for @user, url: { action: "update_picture", id: @user.id } do |f| %>
                <%= f.cropbox :picture, :width => 400 %>
                <div class= "text-center mtop-10">
                  <%= f.submit 'Ma photo est belle', class: "btn btn-pepeat" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-4 col-sm-offset-1">
          <div class="chief-profile-right">
            <div class= "chief-profile-right-date">
              <i class="fa fa-cutlery awesome"></i> <span><%= @user.surname %></span>
            </div>
          <!-- <p> Prénom</p> -->
            <div class= "chief-profile-right-date">
              <i class="fa fa-user awesome"></i> <span><%= @user.firstname %></span>
            </div>
            <!-- <p>Nom</p> -->
            <div class= "chief-profile-right-date">
              <i class="fa fa-user awesome"></i> <%= @user.lastname %>
            </div>
            <!-- <p> Numéro de téléphone</p> -->
            <div class= "chief-profile-right-date">
              <i class="fa fa-mobile awesome"></i> <%= @user.phone_number %>
            </div>
              <!-- <p> Adresse</p> -->
              <div class= "chief-profile-right-date">
                <i class="fa fa-map-marker awesome"></i>
                <% if current_user.address %>
                  <%= @user.address %>
                <% end %>
              </div>

            <!-- <p> Date de naissance</p> -->
            <div class= "chief-profile-right-date">
              <i class="fa fa-birthday-cake awesome"></i>
              <% if  @user.birth %>
                <%= l(@user.birth, format: '%d / %m / %Y') %>
              <% end %>
            </div>
          </div>
        </div>
        <div class=" col-xs-12 col-sm-8 col-sm-offset-2 ">
          <p><%= @user.description.html_safe %> </p>
        </div>
        <div class=" col-xs-12 col-sm-8 col-sm-offset-2 ">
          <div class= "card-infos-map map-margin">
            <div id="map3" style="width: 100%; height: 100%;"></div>
          </div>
          <div class= "text-center chief-profile-modify">
            <%= link_to "Modifier mes informations", edit_profile_path, class: "btn btn-pepeat2" %>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="container">
    <div class= "stripe 3 text-center" id= "redirect-stripe">
      <div class="row">
        <div class="col-xs-12 col-sm-6">
          <div class="stripe-left">
            <%= image_tag 'credit-cards_visa', class: "card-chief-infos-img" %>
            <%= image_tag 'credit-cards_maestro', class: "card-chief-infos-img" %>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6">
          <h1 class= "text-center profile-header">Mes informations bancaires</h1>
          <p>Pour pouvoir transférer vos revenus sur votre compte nous avons besoin de votre RIB.</p>
          <% if current_user.bank_account_id %>
            <% account = Stripe::Account.retrieve(current_user.stripe_id) %>
            <% bank_account = account.external_accounts.retrieve(current_user.bank_account_id) %>
            <h4>Compte actuel : ********<%= bank_account.last4 %></h4>
            <div class= "text-center">
            <%= link_to 'Modifier mon compte bancaire', bank_account_profile_path, class: "btn btn-pepeat2" %>
            </div>
          <% else %>
            <div class= "text-center">
            <%= link_to 'Informations bancaires', bank_account_profile_path, class: "btn btn-pepeat2" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <!-- create chiefpicture hidden form -->

  <div class= "hidden-form">
    <%= simple_form_for(@chief_picture, url: profile_chief_pictures_path, html: { multipart: true }) do |f| %>
      <%= f.error_notification %>
      <%= f.file_field :chiefpicture, id: "pictureInput"%>
      <%= f.button :submit, "GO!", id:"go", class: "btn-lg btn-danger" %>
    <% end %>
  </div>

  <!-- END create chiefpicture hidden form -->

  <div class="container">
    <div class="gallery-kitchen 4">
      <h1 class= "text-center profile-header">Ma galerie photo</h1>
      <div class="row">
        <p class= "text-center"> Mettez ici des photos de votre environnement de travail ainsi que des rencontres que vous avez faites avec Pepeat.</p>
        <p class= "text-center"><b>Important:</b> N'hésitez pas à utiliser l'outil fournit par Pepeat pour redimensionner vos photos.</p>
        <% @user.chief_pictures.each do |picture|%>
          <div class="col-xs-12 col-sm-3">
            <div class="picture-kitchen">
              <%= image_tag picture.chiefpicture.url(:medium), class: "kitchen-size" %>
              <div class= "text-center">
                <%= link_to 'Redimensionner', croping_profile_path(picture), class: "button button-highlight button-tiny" %>
                <%= link_to profile_chief_picture_path(picture),
                method: :delete,
                data: { confirm: "Etes vous certain de vouloir supprimer la photo ?" } do %>
                <button class="button button-caution button-square button-tiny">
                <i class="fa fa-trash"></i>
                </button>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
        <div class= "col-xs-12 col-sm-3">
          <div id= "target3", class= "picture-kitchen">
            <%= image_tag 'placeholder.png', id: "placeholder", class: "kitchen-size" %>
          </div>
          <div id= 'target2'></div>
          <div class= "go-btn invisible" id= "space-btn">
            <%=link_to 'Valider', 'javascript:;', class: 'btn btn-success' %>
          </div>
          <div class= "go-btn invisible modify-btn" id= "change-btn">
            <%=link_to 'Changer', 'javascript:;', class: 'btn btn-danger' %>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="container">
    <div class="card-feedback 5">
      <h1 class= "text-center profile-header">Mes avis</h1>
      <div class="row">
        <% if review(@user) == 0 %>
            <h3 class= "text-center">Vous n'avez pas encore d'avis</h3>
        <% else %>
          <% @user.meals.each do |meal| %>
            <%= render '/shared/review', meal: meal %>
          <% end %>
          <div class= "text-center avis-btn-position">
            <%= link_to 'Voir tous les avis', rating_profile_path, class: "btn btn-pepeat" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% else %>

  <!-- no chief -->

  <div class="container">
    <div class="chief-profile 1">
      <h1 class= "text-center profile-header">Mes informations</h1>
      <div class="row">
        <div class="col-xs-12 col-sm-6">
          <div class="chief-profile-left text-center">
            <div class= "classic-pic">
              <%= image_tag @user.picture.url(:large), class: "user-img img-circle" %>
              </br>
              <div class= "btn btn-success2 crop">
                Redimensionner
              </div>
            </div>
            <div class= "hidden-form cropable">
              <%= form_for @user, url: { action: "update", id: @user.id } do |f| %>
                <%= f.cropbox :picture, :width => 400 %>
                <div class= "text-center mtop-10">
                  <%= f.submit 'Ma photo est belle', class: "btn btn-pepeat" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-4 col-sm-offset-1">
          <div class="chief-profile-right">
            <!-- <p> Prénom</p> -->
            <div class= "chief-profile-right-date">
              <i class="fa fa-user awesome"></i> <span><%= @user.firstname %></span>
            </div>
            <!-- <p>Nom</p> -->
            <div class= "chief-profile-right-date">
              <i class="fa fa-user awesome"></i> <%= @user.lastname %>
            </div>
            <!-- <p> Numéro de téléphone</p> -->
            <div class= "chief-profile-right-date">
              <i class="fa fa-mobile awesome"></i> <%= @user.phone_number %>
            </div>
              <!-- <p> Adresse</p> -->
              <div class= "chief-profile-right-date">
                <i class="fa fa-map-marker awesome"></i>
                <% if current_user.address %>
                  <%= @user.address %>
                <% end %>
              </div>
            <!-- <p> Date de naissance</p> -->
            <div class= "chief-profile-right-date">
              <i class="fa fa-birthday-cake awesome"></i>
              <% if  @user.birth %>
                 <%= l(@user.birth, format: '%d / %m / %Y') %>
              <% end %>
            </div>
            <div class= "text-center">
              <%= link_to "Modifier mes informations", edit_profile_path, class: "btn btn-pepeat2" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<% end %>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      circle = [{lng: <%= @user.longitude %>, lat: <%= @user.latitude %>, radius: 200}]
      circle_options = { strokeColor:"#FECC1F",strokeOpacity: 1, strokeWeight: 3, fillColor: 'transparent' }
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map3' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.addCircles(circle, circle_options);
        handler.addCircles(circle);
        handler.getMap().setOptions({ scrollwheel: false });
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        handler.getMap().setZoom(13);
      });
    })
  <% end %>
<% end %>


<script type="text/javascript">
  analytics.identify(<%= current_user.id %>, <%= raw current_user.traits.to_json%>);
</script>

app/views/profiles/update.html.erb
<h1>Profiles#update</h1>
<p>Find me in app/views/profiles/update.html.erb</p>