config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  authenticate :user, lambda { |user| user.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "users/registrations", confirmations: "users/confirmations" }

  root to: "home#index"

  resources :events, only: [:index] do
    collection do
      get 'update_user'
    end
  end
  resources :meals, only: [:index, :show]
  resources :comments, only: [:create]
  resources :pepeato, only: [:index]

  resource :profile, only: [:show, :edit, :update] do
    collection do
      get 'rating'
    end
    collection do
        get 'croping'
        get 'webhook'
        get 'bank_account'
        patch 'update_picture'
        patch 'update_bank_account'
    end
  end
  resources :publics, only: [:index, :show] do
    collection do
      get 'faq'
      get 'photo'
    end
  end

  namespace :profile do
    resources :chief_pictures, only: [:destroy, :new, :create, :update]
    resources :meal_pictures, only: [:destroy, :new, :create, :update]
    resources :meals do
      collection do
        get 'mealpic'
        get 'mealcrop'
        get 'history'
        get 'validation'
        patch 'update_portion'
      end
    end
    resources :orders do
      resources :payments, only: [:new, :create]
      collection do
        get 'history'
        get 'rating'
        get 'validation'
      end
    end
  end
end

app/views/shared/_cardmeals.html.erb
<div class="meals">
  <div class= <%= "location-#{meal.user.id}" %>>
    <div class="meals-header">
      <div class= "carousel">
        <% if meal.meal_pictures.count != 0 %>
          <% meal.meal_pictures.each do |picture| %>
            <%= link_to meal_path(meal) do %>
              <div class= "item-slick"> <%= image_tag picture.picture.url(:large),class: "img-carousel hvr-fadeIn hvr-grow"%> </div>
            <% end %>
          <% end %>
        <% else %>
          <%= image_tag 'special', class: "img-carousel hvr-fadeIn hvr-grow" %>
        <% end %>
      </div>
      <div class="meals-header-away">
        <% if meal.home? %>
          <h3 class= "text-center">Diner chez le Pepeato</h3>
        <% else %>
          <h3 class= "text-center">À emporter</h3>
        <% end %>
      </div>
      <div class="meals-header-price">
        <%= meal.price %>€
      </div>
      <div class="meals-header-date">
        <%= l(meal.day, format: '%A %d/%m')%>
      </div>
      <div class="meals-header-pic">
        <%= link_to publics_path(meal.user) do %>
          <%=image_tag meal.user.picture.url(:medium), class: "img-circle img-chef-meal" %>
        <% end %>
      </div>
    </div>
    <div class="meals-body">
      <div class="meals-body-menu">
        <div class="meals-body-menu-title">
          <%= link_to meal_path(meal) do %>
            <h3 class= "text-center"><%= meal.title %></h3>
          <% end %>
        </div>
        <% if meal.starter? %>
          <div class= "meals-body-menu-starter">
            <div class= "meals-body-menu-starter-element">
              <b>Entrée: </b> <i> <%= meal.starter %></i>
            </div>
          </div>
        <% else %>
          <div class= "meals-body-menu-starter">
            <div class= "meals-body-menu-starter-element">
             <span><i>Pas d'entrée proposée</i></span>
            </div>
          </div>
        <% end %>
        <% if meal.main? %>
          <div class= "meals-body-menu-starter">
            <div class= "meals-body-menu-starter-element">
              <b>Plat: </b><i><%= meal.main %></i>
            </div>
          </div>
        <% else %>
          <div class= "meals-body-menu-starter">
            <div class= "meals-body-menu-starter-element">
              <span><i>Pas de plat principal proposé</i></span>
            </div>
          </div>
        <% end %>
        <% if meal.dessert? %>
          <div class= "meals-body-menu-starter">
            <div class= "meals-body-menu-starter-element">
              <b>Dessert: </b><i><%= meal.dessert %></i>
            </div>
          </div>
        <% else %>
          <div class= "meals-body-menu-starter">
            <div class= "meals-body-menu-starter-element">
              <span><i>Pas de dessert proposé</i></span>
            </div>
          </div>
        <% end %>
      </div>
      <div class="meals-body-takeaway text-center">
        <div class="row">
          <div class="col-xs-12 col-sm-6">
            <% if meal.home? %>
              <div>
                <%= image_tag 'home2.png', class: "img-take hover", title: "Diner chez le chef" %>
              </div>
              <div class="meals-body-takeaway-hour">
                <p><i><%= meal.home_hour.strftime('%Hh:%M') %> chez le chef</i></p>
              </div>
            <% else %>
              <div>
                <%= image_tag 'take.png', class: "img-take hover", title: "A emporter chez soi" %>
              </div>
              <div class="meals-body-takeaway-hour">
                <p><i><%= meal.start_hour.strftime('%Hh:%M')%> <%= meal.end_hour.strftime('à %Hh:%M') %></i></p>
              </div>
            <% end %>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class= "meals-body-takeaway-portion hover">
              <% if meal.home?%>
                <span class= "size-txt-portion"><%= available_portions(meal)%></span> <span class= "size-portion"><p>places disponibles</p></span>
              <% else %>
                <span class= "size-txt-portion"><%= available_portions(meal)%></span> <span class= "size-portion"><p>parts disponibles</p></span>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="meals-body-footer">
        <% if  DateTime.now.day == meal.day.day &&((meal.takeaway && format(meal.start_hour)) || (meal.home && format(meal.home_hour))) || available_portions(meal) == 0 %>
          <%= link_to "Voir le menu", meal_path(meal), class: "btn btn-success buton-order" %>
        <% elsif DateTime.now.to_date> meal.day %>
          <%= link_to "Voir le menu", meal_path(meal), class: "btn btn-success buton-order" %>
        <% else %>
          <% if current_user == meal.user %>
            <% if meal.orders.count == 0 %>
              <%= link_to 'Modifier mon annonce', edit_profile_meal_path(meal), class: "btn btn-success buton-order" %>
            <% end %>
          <% elsif (meal.day.to_date - DateTime.now.to_date).to_i > 6  %>
            <div class= "hover" title= "Vous ne pouvez pas commander plus de 7 jours avant">
              <%= link_to 'Réservation bientôt disponible', "#", class: "disabled btn btn-success buton-order" %>
            </div>
          <% else %>
            <div class="meals-body-order">
              <%= render "/shared/modale", meal: meal %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_cardmealsshow.html.erb
 <div class="meal">
  <div class="meal-header">
    <div class= "carousel">
      <% meal.meal_pictures.each do |picture| %>
        <%= link_to meal_path(meal) do %>
          <div> <%= image_tag picture.picture.url(:extralarge), class: "img-carousel"%> </div>
        <% end %>
      <% end %>
    </div>
    <div class="meal-header-status">
      <% if meal.home? %>
        <h3 class= "text-center">Diner chez le chef</h3>
      <% else %>
        <h3 class= "text-center">A emporter</h3>
      <% end %>
    </div>
    <div class="meal-header-price">
      <%=(meal.price) %> €
    </div>
    <div class="meal-header-date">
      <% if meal.home? %>
        <%= l(meal.day, format: '%A %d/%m')%> <span><%= meal.home_hour.strftime('%Hh:%M') %></span>
      <% else %>
        <%= l(meal.day, format: '%A %d/%m')%> <span><%= meal.start_hour.strftime('%Hh:%M')%> - <%= meal.end_hour.strftime('%Hh:%M') %></span>
      <% end %>
    </div>
  </div>
  <div class="meal-body">
    <% if meal.starter? %>
      <div class="meal-body-menu-first">
        <%= image_tag 'starter.png', class: "img-menu-show-meal" %>
        <div class= "meal-body-menu-first-element">
          <p><b><%= meal.starter %></b></p>
        </div>
      </div>
    <% end %>
    <% if meal.main? %>
      <div class="meal-body-menu">
        <%= image_tag 'main.png', class: "img-menu-show-meal" %>
        <div class= "meal-body-menu-element">
          <p><b><%= meal.main %></b></p>
        </div>
      </div>
    <% end %>
    <% if meal.dessert? %>
      <div class="meal-body-menu">
        <%= image_tag 'dessert.png', class: "img-menu-show-meal" %>
        <div class= "meal-body-menu-element">
          <p><b><%= meal.dessert %></b></p>
        </div>
      </div>
    <% end %>
    <div class="meal-body-description">
      <h3 class= "text-center"> A propos du menu </h3>
      <p><%= meal.description.html_safe %></p>
    </div>
    <div class="meal-body-infos text-center">
      <div class="row">
        <div class="col-xs-12 col-sm-6">
          <% if meal.home? %>
            <div>
              <%= image_tag 'home2.png', class: "img-take hover", title: "Diner chez le chef" %>
            </div>
            <div class="meals-body-takeaway-hour">
              <i>Rdv à <%= meal.home_hour.strftime('%Hh:%M') %> chez le chef</i>
            </div>
          <% else %>
            <div>
              <%= image_tag 'take.png', class: "img-take hover", title: "A emporter chez sois" %>
            </div>
            <div class="meals-body-takeaway-hour">
              <i><%= meal.start_hour.strftime('%Hh:%M')%> <%= meal.end_hour.strftime('à %Hh:%M') %></i>
            </div>
          <% end %>
        </div>
        <div class="col-xs-12 col-sm-6">
          <div class= "meals-body-takeaway-portion">
            <span class= "size-txt-portion"><%= available_portions(meal)%></span> <%= image_tag 'portion.svg', class: "size-portion" %>
          </div>
        </div>
      </div>
    </div>
    <% if DateTime.now.day == meal.day.day && ((meal.takeaway && format(meal.start_hour)) || (meal.home && format(meal.home_hour))) || available_portions(meal) == 0 %>
      <%= link_to "Menu indisponible", '', class: "disabled btn btn-danger buton-order" %>
    <% else %>
      <% if current_user == meal.user %>
          <% if meal.orders.count == 0 %>
            <%= link_to 'Modifier mon annonce', edit_profile_meal_path(meal), class: "btn btn-success buton-order" %>
          <% end %>
        <% elsif (meal.day.to_date - DateTime.now.to_date).to_i > 6  %>
          <div class= "hover" title= "Vous ne pouvez pas commander plus de 7 jours avant">
            <%= link_to 'Réservation bientôt disponible', "#", class: "disabled btn btn-success buton-order" %>
          </div>
        <% else %>
          <div class="meals-body-order">
            <%= render "/shared/modale", meal: meal %>
          </div>
        <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
    <div class="home-alert">
      <div class="alert alert-info alert-dismissible slideDown fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert", role:"button", aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
    </div>
  <% end %>
  <% if alert %>
    <div class="home-alert">
      <div class="alert alert-warning alert-dismissible slideDown fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= alert %>
      </div>
    </div>
  <% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="footer-infos text-center">
      <div class="row">
        <div class="col-xs-4">
          <h1>Pepeat</h1>
          <p><%= link_to 'Inscription', new_user_registration_path %></p>
          <p><%= link_to 'Connexion', new_user_session_path %></p>
        </div>
        <div class="col-xs-4">
          <h1>Legal</h1>
          <p><%= link_to 'CGU', '#' %></p>
          <p><%= link_to 'Mentions légales', '#' %></p>
        </div>
        <div class="col-xs-4">
          <h1>Cuisiniers</h1>
          <p><%= link_to 'Rejoignez Pepeat', page_path('chief_infos') %></p>
          <p><%= link_to 'FAQ', faq_publics_path, :target => "_blank" %></p>
          <p><%= link_to 'Tutoriel photos', photo_publics_path, :target => "_blank" %></p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class=" col-xs-4 col-sm-1 col-sm-offset-5">
        <div class= "footer-social text-center">
          <%= link_to "https://www.facebook.com/PepeatLaCusineDeVosVoisinsDansVotreAssiette/", :target => "_blank" do %>
            <div class= "footer-social-item hvr-grow" >
              <i class="fa fa-facebook footer-social-item-fafa"></i>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-xs-4 col-sm-1">
        <div class= "footer-social text-center">
          <%= link_to "https://twitter.com/pepeat_cuisine",:target => "_blank" do %>
            <div class= "footer-social-item hvr-grow" >
              <i class="fa fa-twitter footer-social-item-fafa"></i>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-xs-4 col-sm-1">
        <div class= "footer-social text-center">
          <%= link_to "https://www.instagram.com/pepeat_cuisine/", :target => "_blank" do %>
            <div class= "footer-social-item hvr-grow" >
              <i class="fa fa-instagram footer-social-item-fafa"></i>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class= "text-center">
      <h1>Réalisé à Lille avec <i class="fa fa-heart"></i> par les équipes de Pepeat</h1>
      <a href="https://mixpanel.com/f/partner" rel="nofollow"><img src="//cdn.mxpnl.com/site_media/images/partner/badge_light.png" alt="Mobile Analytics" /></a>
    </div>
  </div>
</div>

app/views/shared/_modale.erb
<a data-toggle="modal" data-target="#booking-<%=meal.id%>">
  <b class= "btn btn-success buton-order">Je commande ce menu</b>
</a>


<div class="modal fade" id="booking-<%=meal.id%>">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center">Commandez ici</h4>
      </div>
      <%= simple_form_for [meal, @order], url: profile_orders_path do |f| %>
        <div class="modal-body">
          <%= f.input :portion, label: 'Combien de parts voulez vous commander ?',required: false, collection: 1..available_portions(meal), input_html: {class: "input-lg"}, prompt: "aucune part choisie" %>
          <%= f.input :meal_id, as: :hidden, :input_html => { :value => meal.id }%>
          <%= f.input :amount, as: :hidden, :input_html => { :value => meal.price } %>
          <%= f.input :state, as: :hidden,  :input_html => { :value => 'pending' }%>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
          <%= f.button :submit, value: 'Réservez maintenant', label: 'Réservez maintenant', class: "btn btn-pepeat btn-lg" %>
        </div><!-- /.modal-content -->
      <% end %>
    </div><!-- /.modal-dialog -->
  </div>
</div><!-- /.modal -->

app/views/shared/_modale.html.erb
<div class="modal fade" id="booking-<%=meal.id%>">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center">Choisissez le nombre de menus</h4>
      </div>
      <%= simple_form_for [meal, @order], url: profile_orders_path do |f| %>
        <div class="modal-body text-center">
          <div class="row">
            <div class="col-xs-6 col-xs-offset-3">
              <%= image_tag 'pepeat.png', class: "modal-body-logo" %>
              <div class= "">
                <%= f.input :portion, label: false,required: false, collection: 1..available_portions(meal), input_html: {class: "input-lg"}, prompt: "aucun menu choisi", selected: 1 %>
              </div>
              <%= f.input :meal_id, as: :hidden, :input_html => { :value => meal.id }%>
              <%= f.input :amount, as: :hidden, :input_html => { :value => meal.price } %>
              <%= f.input :state, as: :hidden,  :input_html => { :value => 'pending' }%>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <!-- <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button> -->
          <div class= "text-center">
            <%= f.button :submit, value: 'Réserver maintenant', label: 'Réserver maintenant', class: "btn btn-success" %>
          </div>
        </div><!-- /.modal-content -->
      <% end %>
    </div><!-- /.modal-dialog -->
  </div>
</div><!-- /.modal -->

<div>
  <a data-toggle="modal" data-target="#booking-<%=meal.id%>">
    <b class= "btn btn-success buton-order" id="order-click">Je commande ce menu</b>
  </a>
</div>

<script type="text/javascript">
  var link = document.getElementById('order-click');
  analytics.trackLink(link, 'I purchase this menu');
</script>

app/views/shared/_modale_delete.html.erb
<div class="modal fade" id="delete-<%=order.id%>">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center">Modalité d'annulation de commandes</h4>
      </div>
      <div class= "modale-delete text-center">
        <p> Si vous annulez votre commande avant minuit du jour de votre réservation</p>
         <h3><b>Vous ne payez aucuns frais.</b></h3>
        <p> Si vous annulez votre commande le jour même</p>
        <h3><i><b>Vous payez la totalité de votre commande</b></i></h3>
       <%= link_to profile_order_path(order),
        method: :delete,
        data: { confirm: "Etes vous certain de vouloir supprimer votre réservation ?" } do %>
        <button class="btn btn-danger2">
          Je supprime ma réservation
        </button>
      <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
      </div>
    </div><!-- /.modal-dialog -->
  </div>
</div><!-- /.modal -->


<a data-toggle="modal" data-target="#delete-<%=order.id%>">
  <button class="btn btn-danger2 hover" title= "Annuler votre réservation">
    <i class="fa fa-trash"></i>
  </button>
</a>

app/views/shared/_modale_pic.html.erb
  <a data-toggle="modal" data-target="#croppable-<%=picture.id%>">
    <b class= "btn btn-success buton-order">modifier</b>
  </a>



<div class="modal fade" id="croppable-<%=picture.id%>">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Cropper votre photo</h4>
      </div>
        <%= simple_form_for picture, url: profile_chief_picture_path(picture) do |f| %>
          <%= f.cropbox :chiefpicture, :width => 300 %>
          <%= f.button :submit, "Je valide mon profil", class: "btn-lg btn-pepeat" %>
        <% end %>
    </div><!-- /.modal-dialog -->
  </div>
</div><!-- /.modal -->

app/views/shared/_navbar.html.erb
<% if request.original_url == "http://localhost:3000/" || request.original_url == 'https://pepeat-v2-production.herokuapp.com/' || request.original_url == 'https://www.pepeat.org/'%>
  <nav class="navbar navbar-default navbar-fixed-top navbar-wagon2 navbar-absolute" role="navigation">
<% else %>
 <nav class="navbar navbar-default navbar-fixed-top navbar-wagon navbar-absolute" role="navigation">
<% end %>
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      <a class="navbar-brand" href="/">
        <%= image_tag "pepeat.png" %>
      </a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <%= link_to "#", {class: "dropdown-toggle", "data-toggle" => "dropdown", "role" => "button", "aria-expanded" => "false"} do %>
                <%= image_tag current_user.picture.url(:thumb), class: "img-avatar" %>
              <%= current_user.firstname %> <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu" role="menu">
              <li>
                <%= link_to profile_path do %>
                  <%= t ".profile", default: "Mon profil" %>
                <% end %>
              </li>
              <% if current_user.chief? %>
                <li>
                  <%= link_to rating_profile_path do %>
                    Mes avis
                  <% end %>
                </li>
              <% end %>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Déconnection" %>
                <% end %>
              </li>
            </ul>
          </li>
          <% if current_user.chief? %>
            <li class= "dropdown">
               <%= link_to "#", {class: "dropdown-toggle", "data-toggle" => "dropdown", "role" => "button", "aria-expanded" => "false"} do %>
                <i class="fa fa-cutlery"></i> Cuisine <span class="caret"></span>
              <% end %>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to profile_meals_path do %>
                    Mes annonces
                  <% end %>
                </li>
                <li>
                  <%= link_to history_profile_meals_path do %>
                    Mon historique
                  <% end %>
                </li>
              </ul>
            </li>
          <% end %>
          <li class= "dropdown">
             <%= link_to "#", {class: "dropdown-toggle", "data-toggle" => "dropdown", "role" => "button", "aria-expanded" => "false"} do %>
              <i class="fa fa-shopping-cart"></i> Réservations <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu" role="menu">
              <li>
                <%= link_to profile_orders_path do %>
                  En cours
                <% end %>
              </li>
              <li>
                <%= link_to history_profile_orders_path do %>
                  Mon historique
                <% end %>
              </li>
            </ul>
          </li>
          <li>
            <%= link_to events_path do %>
              SharingLille
            <% end %>
          </li>
          <li>
            <%= link_to pepeato_index_path do %>
              Les Pepeato
            <% end %>
          </li>
          <li class= "dropdown">
             <%= link_to "#", {class: "dropdown-toggle", "data-toggle" => "dropdown", "role" => "button", "aria-expanded" => "false"} do %>
              <i class="fa fa-question-circle"></i> Aide <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu" role="menu">
              <li>
                <%= link_to page_path('pepeato') do %>
                  Pepeato
                <% end %>
              </li>
              <li>
                <%= link_to  history_profile_meals_path do %>
                  <!-- Utilisateur -->
                <% end %>
              </li>
            </ul>
          </li>
          <li>
            <%= link_to t(".top_call_to_action", default: "Voir les menus"), meals_path, class: "btn2", id: 'navbar-action' %>
          </li>
          <li>
            <% if current_user.chief? %>
              <%= link_to t(".top_call_to_action", default: " Créer un menu"), new_profile_meal_path, class: "btn", id: 'create-menu' %>
            <% else %>
              <%= link_to t(".top_call_to_action", default: "Devenir Pepeato"), page_path('chief_infos'), class: "btn", id: "pepeato-in-action" %>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to t(".sign_up", default: "S'inscrire"), new_user_registration_path %>
          </li>
          <li>
            <%= link_to t(".sign_in", default: "Se connecter"), new_user_session_path %>
          </li>
          <li>
            <%= link_to events_path do %>
              SharingLille
            <% end %>
          </li>
          <li>
            <%= link_to pepeato_index_path do %>
              Les Pepeato
            <% end %>
          </li>
          <li class= "dropdown">
             <%= link_to "#", {class: "dropdown-toggle", "data-toggle" => "dropdown", "role" => "button", "aria-expanded" => "false"} do %>
              <i class="fa fa-question-circle"></i> Aide <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu" role="menu">
              <li>
                <%= link_to page_path('pepeato') do %>
                  Pepeato
                <% end %>
              </li>
              <li>
                <%= link_to  history_profile_meals_path do %>
                  <!-- Utilisateur -->
                <% end %>
              </li>
            </ul>
          </li>
          <li>
            <%= link_to t(".top_call_to_action", default: "Voir les menus"), meals_path, class: "btn2", id: 'navbar-action' %>
          </li>
          <li>
            <%= link_to t(".top_call_to_action", default: "Devenir Pepeato"), page_path('chief_infos'), class: "btn", id: 'pepeato-out-action' %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<script type="text/javascript">
  var link = document.getElementById('navbar-action');
  analytics.trackLink(link, 'Navbar clicked voir les menus');
</script>

<script type="text/javascript">
  var link = document.getElementById('pepeato-out-action');
  analytics.trackLink(link, 'Pepeato out navbar');
</script>

<script type="text/javascript">
  var link = document.getElementById('pepeato-in-action');
  analytics.trackLink(link, 'Pepeato in navbar');
</script>

<script type="text/javascript">
  var link = document.getElementById('create-menu');
  analytics.trackLink(link, 'Create menu');
</script>

app/views/shared/_ordershow.html.erb
<div class="margin">
  <div class="meal">
    <div class="meal-header">
      <div class= "carousel">
        <% meal.meal_pictures.each do |picture| %>
          <%= link_to meal_path(meal) do %>
            <div> <%= image_tag picture.picture.url(:extralarge), class: "img-carousel"%> </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="meal-body">
      <% if meal.starter? %>
        <div class="meal-body-menu-first">
          <%= image_tag 'starter.png', class: "img-menu-show-meal" %>
          <div class= "meal-body-menu-first-element">
            <%= meal.starter %>
          </div>
        </div>
      <% end %>
      <% if meal.main? %>
        <div class="meal-body-menu">
          <%= image_tag 'main.png', class: "img-menu-show-meal" %>
          <div class= "meal-body-menu-element">
            <%= meal.main %>
          </div>
        </div>
      <% end %>
      <% if meal.dessert? %>
        <div class="meal-body-menu">
          <%= image_tag 'dessert.png', class: "img-menu-show-meal" %>
          <div class= "meal-body-menu-element">
            <%= meal.dessert %>
          </div>
        </div>
      <% end %>
      <div class="meal-body-description">
        <h3 class= "text-center"> A propos du menu </h3>
        <%= meal.description.html_safe %>
      </div>
    </div>
  </div>
</div>