config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  authenticate :user, lambda { |user| user.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "users/registrations", confirmations: "users/confirmations" }

  root to: "home#index"

  resources :events, only: [:index] do
    collection do
      get 'update_user'
    end
  end
  resources :meals, only: [:index, :show]
  resources :comments, only: [:create]
  resources :pepeato, only: [:index]

  resource :profile, only: [:show, :edit, :update] do
    collection do
      get 'rating'
    end
    collection do
        get 'croping'
        get 'webhook'
        get 'bank_account'
        patch 'update_picture'
        patch 'update_bank_account'
    end
  end
  resources :publics, only: [:index, :show] do
    collection do
      get 'faq'
      get 'photo'
    end
  end

  namespace :profile do
    resources :chief_pictures, only: [:destroy, :new, :create, :update]
    resources :meal_pictures, only: [:destroy, :new, :create, :update]
    resources :meals do
      collection do
        get 'mealpic'
        get 'mealcrop'
        get 'history'
        get 'validation'
        patch 'update_portion'
      end
    end
    resources :orders do
      resources :payments, only: [:new, :create]
      collection do
        get 'history'
        get 'rating'
        get 'validation'
      end
    end
  end
end

app/views/pages/chief_infos.html.erb
<div id= "banner" class= "background-banner" >
  <div class= "overlay">
    <div class= "content text-center">
      <h3>Pepeato</h3>
      <h1>Partagez votre passion de la cuisine et vendez vos menus avec Pepeat</h1>
       <div class= "text-center button-chief">
        <%= link_to "Je deviens Pepeato", edit_profile_path(chief: true), class: "btn-lg btn-pepeat2", id: "Pepeato action create" %>
      </div>
      </div>
    </div>
  </div>
</div>


<div id= "infos" class="infos-chief text-center">
  <h2 class= "text-center">Qu'est ce qu'un Pepeato ?</h2>
  <div class="container">
    <div class="row organisation-row">
      <div class="col-xs-12 col-sm-4">
        <%= image_tag 'chef-maison' %>
        <!-- <div class= "position-sticker">
          <div class="sticker statut" data-sr='enter left over 1.3s scale up 20% reset'>
          </div>
        </div> -->
      </div>
      <div class="col-xs-12 col-sm-8">
        <div class= "description-chief text-center">
          <h1> Tout le monde peut devenir Pepeato à condition d'être passionné de cuisine !</h1>
          <p><b>Amateur :</b> Vous êtes créatif aux fourneaux, vous aimez cuisiner et passer du temps à préparer des bons plats ? Devenez Pepeato et partagez votre passion en vendant vos menus à votre voisinnage.</p>
          <p><b>Professionel :</b> Devenez Pepeato et profitez d'un réseau de clients curieux pour tester vos nouvelles recettes et vendre vos réalisations. </p>
          <p><b>Étudiant en restauration : </b> Devenir Pepeato vous permettra de tester votre talent et d'alléger vos frais de cuisine.</p>
        </div>
      </div>
    </div>
    <div class="row organisation-row">
      <div class="col-xs-12 col-sm-4">
        <%= image_tag 'chef-domicile' %>
        <!-- <div class= "position-sticker">
          <div class="sticker passion" data-sr='enter left over 1.3s scale up 20% reset'>
          </div>
        </div> -->
      </div>
      <div class="col-xs-12 col-sm-8">
        <div class= "description-chief text-center">
          <h1> Un Pepeato est sociable, curieux et passionné</h1>
          <p>Les Pepeato forment une communauté de passionnés de gastronomie qui ramènent les plats faits maison au goût du jour. Pour cela il faut évidemment cuisiner mais aussi être sociable et curieux de rencontrer son voisinnage. Les Pepeato sont les ambassadeurs Pepeat ! </p>
        </div>
      </div>
    </div>
    <div class="row organisation-row">
      <div class="col-xs-12 col-sm-4">
        <%= image_tag 'chef-cuisine' %>
       <!--  <div class= "position-sticker">
          <div class="sticker hygiene" data-sr='enter left over 1.3s scale up 20% reset'>
          </div>
        </div> -->
      </div>
      <div class="col-xs-12 col-sm-8">
        <div class= "description-chief text-center">
          <h1> Un Pepeato veille à la qualité de ses préparations</h1>
          <p> Les Pepeato doivent garantir une qualité maximale pour leurs clients. Il/Elle cuisine dans un environnement sain et respecte les procédures classiques de cuisine. Le Pepeato ne distribue jamais un plat cuisiné la veille ! Les clients donnent leur avis sur chaque Pepeato après leurs commandes.</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="pepeato-fonct text-center">
  <h2>Tout est simple avec Pepeat</h2>
  <h3>Vous choisissez . . . </h3>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <div class="pepeato-fonct-card">
          <div class="row">
            <div class="col-xs-12 col-sm-8">
              <div class="pepeato-fonct-card-left">
                <b><h2> . . . quand vous cuisinez</h2></b>
                <p>Vous êtes totalement libre de cuisiner quand bon vous semble. Il vous suffit de fixer un jour et une tranche horaire et le tour est joué !</p>
              </div>
            </div>
            <div class="col-xs-12 col-sm-4">
              <div class="pepeato-fonct-card-right">

              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="pepeato-fonct-card">
          <div class="row">
            <div class="col-xs-12 col-sm-8">
              <div class="pepeato-fonct-card-left">
                <b><h2>. . . ce que vous cuisinez</h2></b>
                <p>Entrée, plat, dessert ou un menu complet. Il vous appartient de concoter ce que vous voulez, c'est votre cuisine non ? </p>
              </div>
            </div>
            <div class="col-xs-12 col-sm-4">
              <div class="pepeato-fonct-card-right2">

              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="pepeato-fonct-card">
          <div class="row">
            <div class="col-xs-12 col-sm-8">
              <div class="pepeato-fonct-card-left">
                <b><h2> . . . pour combien de personnes vous cuisinez</h2></b>
                <p>Vous avez une grande cuisine et la capacité de faire un menu pour 30 personnes, aucun problème. Vous avez peu de place et pouvez préparer un repas pour 4 personnes, toujours aucun problème.</p>
              </div>
            </div>
            <div class="col-xs-12 col-sm-4">
              <div class="pepeato-fonct-card-right3">

              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="pepeato-fonct-card">
          <div class="row">
            <div class="col-xs-12 col-sm-8">
              <div class="pepeato-fonct-card-left">
                <b><h2> . . . le prix que vous voulez</h2></b>
                <p>C'est à vous de juger le prix de votre menu. Mais attention, s'il est trop cher, cela risque de faire fuir les potentiels clients. Pepeat conseille de fixer le prix d'un menu complet ( entrée, plat, dessert) entre 8€ et 12€.</p>
              </div>
            </div>
            <div class="col-xs-12 col-sm-4">
              <div class="pepeato-fonct-card-right4">

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="pepeato-order text-center">
  <h3>Et vous préparez . . .</h3>
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="pepeato-order-card">
          <div class="row">
            <div class="col-xs-12 col-sm-3">
              <div class="pepeato-order-card-superleft">
              </div>
            </div>
            <div class="col-xs-12 col-sm-6">
              <div class="pepeato-order-card-left">
                <h2> . . . votre menu en toute sérénité</h2>
                <p><i class="fa fa-check"></i>Les commandes s'arrêtent <b>4h avant</b> l'heure que vous avez fixée.</p>
                <p><i class="fa fa-check"></i>Vous faites les courses et la cuisine <b>uniquement pour les personnes qui ont commandé</b>. Pas de gachis, pas de surplus.</p>
                <p><i class="fa fa-check"></i>Vous recevez vos voisins chez vous à l'heure prévue. Pas besoin de parler d'argent, <b>le transfert est automatique</b> et arrivera dans 1 semaine sur votre compte.</p>
              </div>
            </div>
            <div class="col-xs-12 col-sm-3">
              <div class="pepeato-order-card-right">

              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<div class="convaincu text-center">
  <div class="container">
    <h2>Convaincu ?</h2>
    <h3>N'attendez plus et créez votre profil en 2 minutes.</h3>
    <div class= "text-center button-chief">
      <%= link_to "Je deviens Pepeato", edit_profile_path(chief: true), class: "btn-lg btn-pepeat", id: "Pepeato action create" %>
    </div>
  </div>
</div>


<script type="text/javascript">
  analytics.track('Pepeato-infos')
</script>

<script type="text/javascript">
  var link = document.getElementById('Pepeato action create');
  analytics.trackLink(link, 'Pepeato action create');
</script>

app/views/pages/pepeato.html.erb
<div id= "banner" class= "background-banner" >
  <div class= "overlay">
    <div class= "content text-center">
      <h3>Pepeato</h3>
       <div class= "text-center button-chief">
        <%= link_to "Je crée un profil de Pepeato", edit_profile_path(chief: true), class: "btn-lg btn-pepeat2", id: "Pepeato action create" %>
      </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-3">
    <div class="before-sidebar">
    <div class="sidebar window-height">
      <ul class="nav nav-pills nav-stacked" role="tablist">
        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Créer un menu</a></li>
        <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Gérer ses commandes</a></li>
        <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Recevoir ses revenus</a></li>
        <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Recevoir ses clients</a></li>
        <li role="presentation"><a href="#pepeatbox" aria-controls="pepeatbox" role="tab" data-toggle="tab">PepeatBox</a></li>
        <li role="presentation"><a href="#picture" aria-controls="picture" role="tab" data-toggle="tab">Photos et présentation</a></li>
        <li role="presentation"><a href="#cancel" aria-controls="cancel" role="tab" data-toggle="tab">En cas d'annulation</a></li>
        <li role="presentation"><a href="#when" aria-controls="when" role="tab" data-toggle="tab">À quel moment cuisiner</a></li>
        <li role="presentation"><a href="#price" aria-controls="price" role="tab" data-toggle="tab">Prix et quantité</a></li>
        <li role="presentation"><a href="#hygiene" aria-controls="hygiene" role="tab" data-toggle="tab">Hygiène et sécurité</a></li>
      </ul>
    </div>
    </div>
  </div>
  <div class="col-xs-9">
    <div class="tab-content">

      <div role="tabpanel" class="tab-pane fade in active" id="home">
        <div class="container-fluid">
          <div class="menu text-center">
            <div class="row">
              <h1 class= "text-center">Créer un menu</h1>
                <div class="col-xs-6">
                  <div class="menu-item">
                    <%= image_tag 'picture.png'%>
                    <h2 class= "text-center">Règle numéro 1</h2>
                    <p>Toujours avoir des photos de son menu avant de le créer.</p>
                  </div>
                </div>
                <div class="col-xs-6">
                    <div class="menu-item">
                    <%= image_tag 'place.png'%>
                    <h2 class= "text-center">Règle numéro 2</h2>
                    <p>Faire très attention au choix "sur place" ou "à emporter".</p>
                  </div>
                </div>
                <div class="col-xs-6">
                  <div class="menu-item">
                    <%= image_tag 'prix.png'%>
                    <h2 class= "text-center">Règle numéro 3</h2>
                    <p>Ne pas fixer des prix trop élevés pour rester attractif.</p>
                  </div>
                </div>
                <div class="col-xs-6">
                  <div class="menu-item">
                    <%= image_tag 'capacity.png'%>
                    <h2 class= "text-center">Règle numéro 4</h2>
                    <p>Prévoir un nombre de menus en adéquation avec la taille de sa cuisine.</p>
                  </div>
                </div>
            </div>
            <div>
              <h4>À vous de jouer</h4>
              <% if current_user && current_user.chief? %>
                <%= link_to 'Créer un menu', new_profile_meal_path, class: "btn btn-lg btn-pepeat2" %>
              <% else %>
                <%= link_to 'Devenir Pepeato', page_path('chief_infos'), class: "btn btn-lg btn-pepeat2" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div role="tabpanel" class="tab-pane fade" id="profile">
        <div class="container-fluid">
          <div class="p-order text-center">
            <h1>Gérer une commande</h1>
            <p>Accédez à votre annonce dans votre espace cuisine</p>
            <%= image_tag 'annonce'%>
            <p>Vous pouvez voir en bas de la carte les personnes ayant commandé votre menu. La photo a une bordure rouge ce qui signifie que votre client n'a pas validé la reception de son menu.</p>
            <p>Ce dernier devra la valider <b>lorsqu'il récupèrera sa commande chez vous.</b></p>
            <%= image_tag 'annonce-2'%>
            <p>En cliquant sur sa photo, vous obtenez les informations nécessaires sur votre client et sa commande.</p>
            <%= image_tag 'annonce-3'%>
            <p><i class="fa fa-trash"></i> Supprimer une commande est irréversible. Un mail automatique sera envoyé pour prévenir les personnes ayant réservé votre menu. </p>
            <p><i class="fa fa-pencil"></i> Vous pouvez uniquement modifier votre menu si vous avez aucune réservation. Le cas échéant, vous êtes obligé de le supprimer pour ensuite en créer un nouveau. Faites donc bien attention lors de votre première création. </p>
          </div>
        </div>
      </div>

      <div role="tabpanel" class="tab-pane fade" id="messages">
        <div class="container-fluid">
          <div class="p-revenus text-center">
            <h1>Recevoir ses revenus sur son compte bancaire</h1>
            <%= image_tag 'revenu'%>
            <p>Pour recevoir vos revenus sur votre compte <b>il vous suffit d'indiquer votre IBAN </b>. Cela ne vous prendra que quelques secondes. </p>
            <p>Vous recevrez vos revenus <b>une semaine </b> après avoir cuisiner votre menu.</p>
            <%= link_to 'Ajouter mon IBAN', bank_account_profile_path, class: "btn btn-lg btn-pepeat2" %>
          </div>
        </div>
      </div>

      <div role="tabpanel" class="tab-pane fade" id="settings">
        <div class="container-fluid">
          <div class="p-customer text-center">
            <h1>Accueillir vos clients avec le sourire</h1>
            <%= image_tag 'jade' %>
            <p>Comme vous l'avez surement compris <b>vous êtes le chef de votre cuisine</b> et vous gérez votre clientèle vous même. </p>
            <p>Au-delà du "manger frais", maison, moins cher, diversifié et local, les valeurs de Pepeat comportent aussi le rapprochement social entres voisins. Nous mettons donc un point d'honneur à ce que nos Pepeato partagent ces mêmes valeurs et <b>accueillent leurs clients dans la bonne humeur et la bienveillance.</b></p>
          </div>
        </div>
      </div>

      <div role="tabpanel" class="tab-pane fade" id="pepeatbox">
        <div class="text-center">
          <%= image_tag 'construction', class: "construction" %>
        </div>
      </div>

      <div role="tabpanel" class="tab-pane fade" id="picture">
       <div class="container-fluid">
          <div class="p-picture text-center">
            <%= image_tag "picture" %>
            <h3>Prendre des photos de plats n'est pas aussi simple que l'on croit</h3>
            <p>Pour vous aider, nous vous avons concocté les bonnes pratiques pour <b>faire des photos vendeuses et jolies</b> qui feront tomber vos menus comme des petits pains.</p>
            <%= link_to 'Tutoriel photos', photo_publics_path, :target => "_blank", class: "btn btn-lg btn-pepeat2" %>
          </div>
        </div>
      </div>

      <div role="tabpanel" class="tab-pane fade" id="cancel">
        <div class="container-fluid">
          <div class="b-cancel">
            <div class="text-center">
              <div class="row">
                <div class="col-xs-12 col-sm-6">
                  <div class="p-cancel-left">
                    <h3>Quand le Pepeato annule</h3>
                    <p>Le Pepeato est maître de sa cuisine, en conséquence <b>il peut annuler quand il le désire.</b></p> <p>Les personnes ayant réservé seront <b>prévénues automatiquement par mail.</b></p><p> Cependant, si un Pepeato annule sans raison valable trop souvent, il ne sera plus autorisé à cuisiner.</p>
                    <p></p>
                  </div>
                </div>
                <div class="col-xs-12 col-sm-6">
                  <div class="p-cancel-right">
                    <h3>Quand le client annule</h3>
                    <div class="p-cancel-right-first">
                      <h4>Plus de un jour avant le TakeAway</h4>
                      <p> Dans ce cas ci, la commande est annulée et <b>le client ne sera pas débité.</b></p>
                      <p>Vous recevrez un mail pour vous prévenir qu'une personne a annulé sa commande.</p>
                    </div>
                    <div class="p-cancel-right-second">
                      <h4>Le jour même</h4>
                      <p> Si le client annule sa commande le jour même, vous <b>recevez l'entièreté du montant de la commande.</b></p>
                      <p>Vous recevrez un mail pour vous prévenir qu'une personne a annulé sa commande.</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div role="tabpanel" class="tab-pane fade" id="when">
        <div class="text-center">
          <%= image_tag 'construction', class: "construction" %>
        </div>
      </div>

      <div role="tabpanel" class="tab-pane fade" id="price">
        <div class="text-center">
          <%= image_tag 'construction', class: "construction" %>
        </div>
      </div>

      <div role="tabpanel" class="tab-pane fade" id="hygiene">
        <div class="text-center">
          <%= image_tag 'construction', class: "construction" %>
        </div>
      </div>

    </div>
  </div>
</div>