config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  authenticate :user, lambda { |user| user.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "users/registrations", confirmations: "users/confirmations" }

  root to: "home#index"

  resources :events, only: [:index] do
    collection do
      get 'update_user'
    end
  end
  resources :meals, only: [:index, :show]
  resources :comments, only: [:create]
  resources :pepeato, only: [:index]

  resource :profile, only: [:show, :edit, :update] do
    collection do
      get 'rating'
    end
    collection do
        get 'croping'
        get 'webhook'
        get 'bank_account'
        patch 'update_picture'
        patch 'update_bank_account'
    end
  end
  resources :publics, only: [:index, :show] do
    collection do
      get 'faq'
      get 'photo'
    end
  end

  namespace :profile do
    resources :chief_pictures, only: [:destroy, :new, :create, :update]
    resources :meal_pictures, only: [:destroy, :new, :create, :update]
    resources :meals do
      collection do
        get 'mealpic'
        get 'mealcrop'
        get 'history'
        get 'validation'
        patch 'update_portion'
      end
    end
    resources :orders do
      resources :payments, only: [:new, :create]
      collection do
        get 'history'
        get 'rating'
        get 'validation'
      end
    end
  end
end

app/models/meal.rb
# == Schema Information
#
# Table name: meals
#
#  id              :integer          not null, primary key
#  main            :string
#  starter         :string
#  dessert         :string
#  price_cents     :integer          default(0), not null
#  portion         :integer
#  description     :text
#  day             :datetime
#  start_hour      :datetime
#  end_hour        :datetime
#  user_id         :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  start_hour_home :datetime
#  takeaway        :boolean
#  title           :string
#  home            :boolean
#  home_hour       :datetime
#  validation      :boolean
#  ingredients     :text
#  cgu             :boolean          default(FALSE)
#
# Indexes
#
#  index_meals_on_user_id  (user_id)



class Meal < ActiveRecord::Base

  monetize :price_cents

  belongs_to :user
  has_many :orders, dependent: :destroy
  has_many :meal_pictures, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :takeaway, presence: true, unless: "home?"
  validates :home, presence: true, unless: "takeaway?"
  validates :start_hour, presence: true, if: "takeaway?"
  validates :end_hour, presence: true, if: "takeaway?"
  validates :home_hour, presence: true, if: "home?"
  validates :day, presence: true
  validates :title, presence: true
  validates :portion, presence: true
  validates :price, presence: true
  validates :ingredients, presence: true

end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  def all(chief)
    @users = []
    chief.each do |user|
      if user.meals.count > 0
        user.meals.each do |meal|
          if meal.day > DateTime.now.to_date - 1.days && meal.validation?
            @users << user
          end
        end
      end
    end
  end

  def is_admin?
  end

  def who_cook(i)
    @people = []
    @meals_selection = []
    @users_0 = []
    @users_1 = []
    @users_2 = []
    @users_3 = []
    @users_4 = []
    @users_5 = []
    @users_6 = []
    Meal.all.each do |meal|
      if ((DateTime.now + i.days).day == meal.day.day || j == meal.day.day) && meal.day > DateTime.now.to_date - 1.days && meal.validation?
        @meals_selection << meal
      end
    end
    @meals_selection.each do |meal|
      if i == 0
        @users_0 << meal.user
      elsif i == 1
        @users_1 << meal.user
      elsif i == 2
        @users_2 << meal.user
      elsif i == 3
        @users_3 << meal.user
      elsif i == 4
        @users_4 << meal.user
      elsif i == 5
        @users_5 << meal.user
      elsif i == 6
        @users_6 << meal.user
      end
    end
  end

  def index
    @meals = policy_scope(Meal)
    @order = Order.new
    # all
    @chief = User.all.where(chief: true)
    all(@chief)
    @markers = Gmaps4rails.build_markers(@users) do |user, marker|
        marker.lat user.latitude
        marker.lng user.longitude
        marker.infowindow "#{user.firstname} #{user.lastname}"
        marker.json({ id: user.id })
    end

    # day 1
    who_cook(0)
    @markers_0 = Gmaps4rails.build_markers(@users_0) do |user, marker|
        marker.lat user.latitude
        marker.lng user.longitude
        marker.json({ id: user.id })
    end

    # day 2
    who_cook(1)
    @markers_1 = Gmaps4rails.build_markers(@users_1) do |user, marker|
        marker.lat user.latitude
        marker.lng user.longitude
        marker.json({ id: user.id })
    end

    # day 3
    who_cook(2)
    @markers_2 = Gmaps4rails.build_markers(@users_2) do |user, marker|
        marker.lat user.latitude
        marker.lng user.longitude
        marker.json({ id: user.id })
    end

    # day 4
    who_cook(3)
    @markers_3 = Gmaps4rails.build_markers(@users_3) do |user, marker|
        marker.lat user.latitude
        marker.lng user.longitude
        marker.json({ id: user.id })
    end

    # day 5
    who_cook(4)
    @markers_4 = Gmaps4rails.build_markers(@users_4) do |user, marker|
        marker.lat user.latitude
        marker.lng user.longitude
        marker.json({ id: user.id })
    end

    # day 6
    who_cook(5)
    @markers_5 = Gmaps4rails.build_markers(@users_5) do |user, marker|
        marker.lat user.latitude
        marker.lng user.longitude
        marker.json({ id: user.id })
    end

    # day 7
    who_cook(6)
    @markers_6 = Gmaps4rails.build_markers(@users_6) do |user, marker|
        marker.lat user.latitude
        marker.lng user.longitude
        marker.json({ id: user.id })
    end

    # day 8
    who_cook(7)
    @markers_7 = Gmaps4rails.build_markers(@users_7) do |user, marker|
        marker.lat user.latitude
        marker.lng user.longitude
        marker.json({ id: user.id })
    end
  end

  def show
    @comment = Comment.new
    @comments = Comment.order('created_at DESC')

    @meal = Meal.find(params[:id])
    authorize @meal
    @order = Order.new
    @user = @meal.user

    @markers = Gmaps4rails.build_markers(@user) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
      marker.picture({
       "url" => "/assets/marker.png",
       "width" =>  0,
       "height" => 0,
       })
    end

  end
end

app/controllers/profile/meals_controller.rb
module Profile
  class MealsController < ApplicationController

    before_action :authenticate_user!
    before_action :is_chief?
    before_action :set_meal, only: [:is_ordered, :show, :edit, :update, :destroy]
    before_action :has_stripe?, only: [:new]
    before_action :is_ordered?, only: [:edit, :update]

    def validation
      @order = Order.find(params[:format])
      ch = Stripe::Charge.retrieve(@order.charge)
      if !ch.captured
        ch.capture
        @order.update(payment_validation: 'true')
        redirect_to profile_meals_path
      else
        redirect_to profile_meals_path
      end
    end

    def index
      @user = current_user
      @meals = policy_scope(Meal)
      @meals = current_user.meals
    end

    def show
    end

    def new
      @user = current_user
      @meal = Meal.new
      authorize @meal
    end

    def create
      @meal = current_user.meals.new(meal_params)
      authorize @meal
      if @meal.save
        MealMailer.creation(@meal.id).deliver_now
        MealMailer.delay_for(5.minutes).validation(@meal.id)

        if !@meal.user.bank_account_id
          MealMailer.delay_for(10.minutes).remember_rib(@meal.id)
        end

        current_user.update(last_meal: DateTime.now)

        if params[:pictures]
          params[:pictures].each { |picture|
            @meal.meal_pictures.create(picture: picture)
          }
        end
         redirect_to mealpic_profile_meals_path(meal_id: @meal.id)
      else
        render :new
      end
    end

    def edit
      @user = current_user
      authorize @meal
    end

    def update
      authorize @meal
      @meal.update(meal_params)
      if @meal.save
        if params[:pictures]
          params[:pictures].each {|picture|
          @meal.meal_pictures.create(picture: picture )
          }
        end
        redirect_to profile_meals_path
      else
        render :edit
      end
    end

    def update_portion
      @meal = Meal.find(params[:format])
      @meal.update(portion_params)
      if @meal.save
        flash[:notice] = 'Le nombre de menus a été modifié'
        redirect_to profile_meals_path
      else
        flash[:notice] = "Nous n'avons pas pu modifier le nombre de menus"
        redirect_to profile_meals_path
      end
    end

    def mealpic
      @meal_picture = MealPicture.new
      @meal = current_user.meals.find(params[:meal_id])
    end

    def mealcrop
      @meal = current_user.meals.find(params[:meal_id])
      @picture = @meal.meal_pictures.find(params[:format])
    end

    def set_meal
      @meal = current_user.meals.find(params[:id])
    end

    def destroy
      authorize @meal
      MealMailer.cancel(@meal.id).deliver_now
      @meal.destroy
      redirect_to profile_meals_path
    end

    def history
      @meals = policy_scope(Meal)
      @meals = current_user.meals
    end

    private

    def is_chief?
      if current_user.chief?
        true
      else
        render :text =>" Ce n'est pas bien de taper des URL au pif. Si vous voulez cuisiner postulez en tant que chef Pepeat"
      end
    end


    def is_ordered?
      if @meal.orders.where(state: "paid").sum(:portion)
        true
      else
        render :text =>" Ce n'est pas bien de taper des URL au pif.Vous ne pouvez supprimer un plat avec des commandes"
      end
    end

    def has_stripe?
      if current_user.stripe_id
        true
      else
        redirect_to profile_path, notice: "Vous devez entrer vos données bancaire avant de créer un menu."
      end
    end

    def portion_params
      params.require(:meal).permit(:portion)
    end

    def meal_params
      params.require(:meal).permit(:cgu, :ingredients, :validation, :home_hour, :home, :starter, :main, :dessert, :price, :title, :portion, :description, :start_hour, :end_hour, :day, :picture, :takeaway)
    end

  end
end

app/helpers/meals_helper.rb
module MealsHelper

  def available_portions(meal)
    meal.portion - booked_portions(meal)
  end

  def booked_portions(meal)
    array= []
    meal.orders.each do |order|
      if order.state == 'paid'
        array << order.portion
      end
    end
    array.sum
  end


  def total_meals(meals)
    array = []
    meals.each do |meal|
      if meal.validation? && meal_actual(meal)
        array << 1
      end
    end
    array.count
  end

  def number_meals(meals, x)
    array = []
    meals.each do |meal|
      if meal.validation? && meal_actual(meal)
        if (DateTime.now + x.days).day == meal.day.day
          array << 1
        end
      end
    end
     array.count
  end


  def meal_actual(meal)
    if meal.day > DateTime.now.to_date - 1.days
      true
    end
  end

  def meal_history(meal)
    if DateTime.now.to_date > meal.day
      true
    end
  end

  def total_recette(meal)
    array = []
    meal.orders.each do |order|
      array << order.meal.price.to_i * order.portion
    end
    array.sum
  end

  def total_recettes(meals)
    array = []
    meals.each do |meal|
      meal.orders.where(state: "paid").each do |order|
        array << order.meal.price.to_i * order.portion - order.meal.price.to_i * order.portion * @chief
      end
    end
    array.sum.round
  end

  def total_meal_sold(meals)
    array = []
    current_user.meals.each do |meal|
      array << meal.orders.where(state: "paid").sum(:portion)
    end
    array.sum
  end


  def notification(meals)
  end

end

app/views/meals/_carousel.html.erb
<div id="carousel-example-generic" class="carousel slide" data-wrap="false" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <% time = meal.meal_pictures.length-1 %>
    <% time.times do %>
      <% i = 1 %>
      <li data-target="#carousel-example-generic" data-slide-to= <% i %>></li>
      <% i += 1 %>
    <% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <% i = 0 %>
    <% meal.meal_pictures.each do |picture| %>
      <% if i == 0 %>
        <div class="item active">
          <%= image_tag picture.picture.url(:medium), class: "size-img-carousel"%>
          <div class="carousel-caption">
          </div>
        </div>
      <% else %>
        <div class="item">
          <%= image_tag picture.picture.url(:medium), class: "size-img-carousel"%>
          <div class="carousel-caption">
          </div>
        </div>
      <% end %>
      <% i += 1 %>
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/meals/_form.html.erb
<div class="form-chat-card">
  <%= simple_form_for(@comment, url: comments_path, remote: true, html: { multipart: true }) do |f|%>
    <div class="form-group">
      <% if current_user.id == meal.user.id %>
        <%= f.label :commenter, 'Répondez ou informez les utilisateurs' %>
      <% else %>
        <%= f.label :commenter, 'Entrez votre question:' %>
      <% end %>
      <%= f.text_area :commenter, rows: 3, class: 'form-control', required: true, maxlength: 2000 %>

      <small class="label label-warning">200 caractères maximum</small>
    </div>
    <%= f.input :meal_id, as: :hidden, input_html: { value: @meal.id } %>
    <%= f.submit 'Je poste', class: 'btn btn-pepeat' %>
  <% end %>
</div>

app/views/meals/_form2.html.erb
<div class="form-chat-card">
  <%= simple_form_for(@comment, url: comments_path, remote: true, html: { multipart: true }) do |f|%>
    <div class="form-group">
      <%= f.label :commenter, 'Entrez votre question:' %>
      <%= f.text_area :commenter, rows: 3, disabled: true, class: 'form-control', required: true, maxlength: 2000, placeholder: "Vous devez vous connecter pour posez votre question" %>

      <small class="label label-warning">200 caractères maximum.</small>
    </div>
    <%= f.input :meal_id, as: :hidden, input_html: { value: @meal.id } %>
    <%= f.submit 'Je poste', class: 'btn btn-pepeat' %>
  <% end %>
</div>

app/views/meals/show.html.erb
<div class="background-meal-new background-banner">
  <div class="overlay">
    <div class="background-meal-new-title text-center">
      <h3><%= @meal.title%></h3>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <%= render "/shared/cardmeals", meal: @meal %>
    </div>
    <div class="col-xs-12 col-sm-6">
      <div class="card-show-chief">
        <div class="carousel">
          <% @meal.user.chief_pictures.each do |picture| %>
            <div> <%= image_tag picture.chiefpicture.url(:large), class: "chief-pic-carousel"%> </div>
          <% end %>
        </div>
        <div class="card-show-chief-img">
          <%= image_tag @meal.user.picture.url(:medium), class: "img-circle picuser" %>
          <%= link_to 'Profil du chef', publics_path(@meal.user), class: "btn btn-pepeat2" %>
        </div>
        <div class="card-show-chief-description">
          <% if @meal.user.description?%>
            <h3 class= "text-center">A propos du chef</h3>
            <%= @meal.user.description.html_safe %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>



<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <div class="meal-description text-center">
        <h2 class= "profile-header">Description du menu</h2>
        <p><%= @meal.description.html_safe%> </p>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">
      <div class="card-ingredients-meal text-center">
        <h1 class= "text-center profile-header">Les ingrédients</h1>
        <%= @meal.ingredients.html_safe %>
      </div>
    </div>
  </div>
</div>


<div class="container">
  <div class="card-order text-center">
    <h1 class= "text-center profile-header">Les commandes</h1>
    <h3 class= "text-center"><%= total_orders(@meal) %> menu(s) commandé(s) </h3>
    <% @meal.orders.where(state: "paid").each do |order| %>
      <span class="card-order-image">
        <%= image_tag order.user.picture.url(:medium), class: "img-circle picuser" %>
        <span class="badge"><%= order.portion%></span>
     </span>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="card-infos">
    <div class="row">
      <div class="col-xs-12 col-sm-4">
        <div class= "card-infos-map">
          <div id="map" style="width: 100%; height: 100%;"></div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-8">
        <h1 class= "text-center profile-header">Les infos</h1>
        <div class="card-infos-plus">
          <div class="card-infos-plus-element text-center">
            <span><p>Adresse de <%=@meal.user.surname %></p></span>
            <p>L'adresse exacte sera disponible après commande.</p>
            <div class= "card-infos-plus-element-position-img">
              <i class="fa fa-map-marker fa-3x"></i>
            </div>
          </div>
          <div class="card-infos-plus-element text-center">
            <% if @meal.home? %>
              <span><p> Jour et heure du rendez vous</p></span>
              <b><%= @meal.day.strftime('%d/%m/%Y') %></b> <%= @meal.home_hour.strftime('%Hh:%M') %>
            <% else %>
              <span><p>Jour et heure du Takeaway</p></span>
              <b><%= @meal.day.strftime('%d/%m/%Y') %></b>  <%= @meal.start_hour.strftime('%Hh:%M')%> - <%= @meal.end_hour.strftime('%Hh:%M') %>
            <% end %>
            <div class= "card-infos-plus-element-position-img">
              <i class="fa fa-calendar fa-3x"></i>
            </div>
          </div>
          <div class="card-infos-plus-order">
            <div class="card-infos-plus-order-buton">
              <% if DateTime.now.day == @meal.day.day && ((@meal.takeaway && format(@meal.start_hour)) || (@meal.home && format(@meal.home_hour))) || available_portions(@meal) == 0 %>
                <%= link_to "Menu indisponible", '', class: "disabled btn btn-danger buton-order" %>
              <% elsif DateTime.now.to_date > @meal.day %>
                <%= link_to "Menu indisponible", '', class: "disabled btn btn-danger buton-order" %>
              <% else %>
                <% if current_user == @meal.user %>
                  <% if @meal.orders.count == 0 %>
                    <%= link_to 'Modifier mon annonce', edit_profile_meal_path(@meal), class: "btn btn-success buton-order" %>
                  <% end %>
                <% elsif (@meal.day.to_date - DateTime.now.to_date).to_i > 6  %>
                  <div class= "hover" title= "Vous ne pouvez pas commander plus de 7 jours avant">
                    <%= link_to 'Réservation bientôt disponible', "#", class: "disabled btn btn-success buton-order" %>
                  </div>
                <% else %>
                  <div class="meals-body-order">
                    <%= render "/shared/modale", meal: @meal %>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="card-chat">
    <h1 class= "text-center profile-header">
      <% if current_user == @meal.user %>
        <%= image_tag @meal.user.picture.url(:medium), class: "img-circle img-chat-chief" %>
      Répondez et informez
      <% else %>
        <%= image_tag @meal.user.picture.url(:medium), class: "img-circle img-chat-chief" %>
      Posez vos questions au chef <%= @meal.user.surname %>
      <% end %>
    </h1>
    <div class="row">
      <% if current_user %>
        <%= render 'form', meal: @meal %>
      <% else %>
        <%= render 'form2', meal: @meal %>
      <% end %>
      <div class="panel panel-default">
        <div class="panel-body">
          <ul class="media-list " id="comments">
            <%= render 'comments/comment', meal: @meal %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="container">
  <div class="card-feedback">
    <h1 class= "text-center profile-header">Les derniers avis de <%= @meal.user.surname %></h1>
    <div class="row">
      <% if review(@user) == 0 %>
          <h3 class= "text-center">Le chef n'a pas encore d'avis</h3>
      <% else %>
        <% @user.meals.each do |meal| %>
          <%= render '/shared/review', meal: meal %>
        <% end %>
        <div class= "text-center avis-btn-position">
          <%= link_to 'Voir tous les avis', public_path(@user), class: "btn btn-pepeat" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      circle = [{lng: <%= @user.longitude %>, lat: <%= @user.latitude %>, radius: 200}]
      circle_options = { strokeColor:"#FECC1F",strokeOpacity: 1, strokeWeight: 3, fillColor: 'transparent' }
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.addCircles(circle, circle_options);
        handler.addCircles(circle);
        handler.getMap().setOptions({ scrollwheel: false });
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        handler.getMap().setZoom(14);
      });
    })
  <% end %>
<% end %>


<% if current_user %>
  <script type="text/javascript">
    analytics.identify(<%= current_user.id %>, <%= raw current_user.traits.to_json%>);
    analytics.track('Meal show', {
  meal_id: '<%= @meal.id %>',
  meal_name: '<%=@meal.title %>',
  meal_price: '<%= @meal.price %>',
  meal_day: '<%= @meal.day %>',
  meal_portion: '<%= @meal.portion%>',
  meal_takeaway: '<%= @meal.takeaway%>',
  meal_chief_id: '<%= @meal.user.id%>',
  meal_chief_id: '<%= @meal.user.surname%>'

});
  </script>
<% else %>
  <script type="text/javascript">
  analytics.track('Meal show', {
  meal_id: '<%= @meal.id %>',
  meal_name: '<%=@meal.title %>',
  meal_price: '<%= @meal.price %>',
  meal_day: '<%= @meal.day %>',
  meal_portion: '<%= @meal.portion%>',
  meal_takeaway: '<%= @meal.takeaway%>',
  meal_chief_id: '<%= @meal.user.id%>',
  meal_chief_id: '<%= @meal.user.surname%>'

});
</script>
<% end %>